### ISSUE TITLE
HashtagRegistry contract, update hashtag

### ISSUE THREAD

**Issue by ghost** [swarmcity/sc-boardwalk-production#111]
The registry should define one of many ways to find a hashtag address.

Registry options
 - minimal costs by just linking ipfs hashes of metadata
 - keeps more data on chain, reports own "total deals"
 - update rep token to add a reference from the rep token back to the hashtag.  Then there isn't a need for a HashRegistry, because hashtags can be defined as the contract linked from any cloned Rep token, which can be found on chain without a custom registry.

Hashtag updates should:
 - increment successfulDeals when rep minted
 - or hashtag's generated ipfs-metadata should include a count of RepAdded event logs.

**Comment by ghost** [comment]
SimpleDeal.sol uses modified SafeMath contract.  Should use zepplin which is a library.

**Comment by kingflurkel** [comment]
Later on the community can sign off on allowed hashtags in the swarm city official build

**Comment by kingflurkel** [comment]
Looking good
