### ISSUE TITLE
Add licence link

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk-production#12]
Add the below multi line comment to the very top of all pages in /test and /src and in index.html
- [x] add  licence link
```
<!--
@license
Copyright (c) 2017 Swarm City
This code may only be used under the license found at https://github.com/swarmcity/license
-->
```

### Test
- [x] Lint one, before copying into all files
- [x] Build, Deploy, Test

**Comment by xardass** [comment]
ok doing that now
