### ISSUE TITLE
get ipfsAddress from contract

### ISSUE THREAD

**Issue by ghost** [swarmcity/sc-boardwalk-production#121]
- [x]  deploy to ropsten
- [ ]  from polymer, use web3 to call 0xb42c0283de4b38c453cb87bbcf10ae24584b6e8a
- [ ]  how to not hard-code the address?
- [ ]  with ipfsAddress, get hashtagMetadata by looking up json file in ipfs

using `curl`, `ethabi` and `jsawk` with `ropsten.infura.io`.

    #!/bin/bash
    IPFS_HASHTAG=`curl -s https://ropsten.infura.io/ -X POST -d '{"jsonrpc":"2.0","id":1,"method":"eth_call","params":[{"to":"0xb42c0283de4b38c453cb87bbcf10ae24584b6e8a","data":"0x1947bd2f0000000000000000000000002e17d4c60a2fc3f1d586d2ca9d66b52f80a043c0"},"latest"]}' | jsawk 'return this.result.slice(2,this.result.length)'` && ethabi decode params -t string $IPFS_HASHTAG | cut -d" " -f2

**Comment by bkawk** [comment]
Re: How to not hard code the address, is there a json file we can import and then read in the address?

**Comment by bkawk** [comment]
I see the getting of the IPFS json as a separate data call, please don't add it to the function to get the hash from the contract.

The display components will first call data-web3 for the hash, .then they will call data-ipfs for the metas data
