### ISSUE TITLE
SWT Price FX Cycle

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk-production#122]
Everywhere a price is displayed, the user should be able to click the price to cycle through different currencies. 

- The default is set to SWT
- The first click cycles to ETH the second click cycles to USD the third is EUR then back to SWT
- When the user selects a different currency all prices in the app are changed to that currency not just the selected one
- Multiple Fx API providers needs to be found 
- This will form its own component that will be applied to others via the slot 
- This will pull data from a new data-fx component that will try multiple providers
- Update the spec on the Wiki
- Insert new component into display-hashtag-deals

**Comment by kingflurkel** [comment]
The value input also changes to the ref currency. Only on the final make deal screen, the SWT value is shown.

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#51
