### ISSUE TITLE
HD Sprite

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk-production#123]
Images not HD, find a way to keep all the images in a single sprite file but also deliver a double density image.

- Recreate sprite in vectors
- Resize sprite for double density
- Check for a better solution than using zoom
- Change png for SVG if we can't find a PNG solution
- Reposition background images to the new sprite size

**Comment by bkawk** [comment]
https://www.andreasnorman.com/how-to-easily-create-image-sprites-for-retina-displays/

**Comment by faffydee** [comment]
![swarmcity-sprite-doublesize](https://user-images.githubusercontent.com/24499354/28928600-e775eebc-786d-11e7-8df9-7029e75810c7.png)
![swarmcity-sprite-normal](https://user-images.githubusercontent.com/24499354/28928601-e7987f40-786d-11e7-933b-d369a31cc0bd.png)

Find the coordinates to each icon here:
https://github.com/swarmcity/sc-boardwalk-production/wiki/CSS-Sprites

**Comment by xardass** [comment]
#184 supersedes
