### ISSUE TITLE
Autofocus button

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk-production#14]
The display component src/displays/display-enter-button.html, uses a span with the role of a button, it can't be auto focused unless its changed into a button.

- [ ] Change the span to a button
- [ ] Ensure the unit tests still work

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_button_autofocus

**Comment by xardass** [comment]
Unit tests were all green on my side (PR #16)
