### ISSUE TITLE
geoslider expanded

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk-production#150]
actual behavior: when clicking on filter, i am asked to give permission to get my location, when allowing I go back to to the screen with the geoslider collapsed, so i need to click on filter again

expected behavior: when clicking on filter, my permission is asked, i give permission and go back to the view i started from, but with the geoslider expanded

relates to exit of page https://github.com/swarmcity/sc-boardwalk-production/wiki/Location

**Comment by n3xco** [comment]
TODO: implement same slider functionality on hashtag page. Currently after geolocation permission is obtained, page returns to hashtag-list instead of hashtag.

**Comment by bkawk** [comment]
This still doesn't feel right, when I arrive on the page the slider is instantly visible and the "filter list" make no sense anymore, maybe 'close slider' or simple X to close it? It also breaks continuity on the hashtag detail page as the filter on that page isn't open.

**Comment by kingflurkel** [comment]
A simple X would do fine imo, let's see what @faffydee thinks/

**Comment by kikipluche** [comment]
stays as is.
