### ISSUE TITLE
Slider routing on Hashtag page

### ISSUE THREAD

**Issue by xardass** [swarmcity/sc-boardwalk-production#158]
actual behavior: when on hashtag page, clicking on filter, i am asked to give permission to get my location, when allowing I go back to hashtag-list page so i need to click on the desired hashtag again

expected behavior: when on hashtag page, clicking on filter, my permission is asked, i give permission and go back to the hashtag page i started from, but with the geoslider expanded.

Possible solutions:
- [ ] Store entry page in session storage.
- [ ] Don't use storage, but use window.history.back()

**Comment by kikipluche** [comment]
@n3xco this is the same issue as #150
