### ISSUE TITLE
Restore

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk-production#19]
A page that is accessed from clicking the restore from backup link on /new. The page animatesin and out with a slide from the right.

### Build

- [x] Make a new page called page-restore.html andd it to swarm-city.html and polymer.json
- [x] Change the animation imports , we need the page to slide in from the right
- [x] Change the animationConfig for entry and exit to slide in and out.
- [x] Use the same css and sprite from /new for the X Esc button top right 
- [x] Pressing Esc will take the user back to /new
- [x] The two buttons should be the same width and stocked one ontop th eother
- [x] Display 2 buttons for 'Restore from IPFS' and 'Restore from backup file'
- [x] Position the two buttons vertically and horizontally center with iron-flex-layout mixins 
- [x] The two buttons should use the --big-btn mixin from shared styles with the text color set to --swarm-city-blue
- [x] The two buttons should have the same on active css and /new
- [x] The user can Tab between the two buttons by setting tab index
- [x] The user can select a button with the enter key or space bar 
- [x] The user can also click the buttons
- [x] On clicking a button set the route to /restore/ipfs or /restore/file when the button is clicked

### Unit Test
- [x]  Both buttons exist
- [x]  Text on the buttons is as expected
- [x]  Clicking a button triggers the correct function (that will update the route)
- [x]  The X Esc button exist
- [x]  Clicking the X button triggers a function

### Visual Test
- [x]  The page animation is silky smooth, with no jitter or delay
- [x]  The buttons are centered vertically and horizontally 
- [x]  The X buttons is in exactly the same location an it is on /new

**Comment by n3xco** [comment]
@bkawk css shared with other pages (pages-new) I could instead add to shared-styles, no?
