### ISSUE TITLE
Hashtag List

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk-production#193]
- [ ] Remove geohash from the hashtag data
- [ ] The Sliders function is to show the user hashtags that have had a deal within the last 24hours in the area selected by the slider.

Note: Although the 24 hours is fixed now it will become variable in the future

**Comment by bkawk** [comment]
Initially, there will be no deals done within 24 hours, so regardless of where the slider is positioned no hashtags will show, it is the responsibility of the hashtag maintainer and the "pioneers" to propagate the link to the [hashtag page](https://github.com/swarmcity/sc-boardwalk-production/wiki/Hashtag) outside of the app, only once a deal is done within a hashtag it will be shown to everyone in the app.

**Comment by bkawk** [comment]
It was revealed that a deal does not have to be done but any activity on the hashtag will keep it visible. For this release, all hashtags will be visible but the need for the variable 24 hour period should be developed now.

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#50
