### ISSUE TITLE
Restore IPFS

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk-production#20]
A page that is accessed from clicking the restore from IPFS link on /restore. The page animates in and out with a slide from the right.

### Build

- [x] make pages/page-restore-ipfs.html and add it to /src/swarm-city.html
- [x] add it as a lazy load and list it under neon-animated-pages.
- [x] add the page to polymer.json as a fragment 
- [x] Use the same animation as found on /restore
- [x] Use the same css and sprite from /new for the X Esc button top right
- [x]  Pressing Esc will take the user back to /new
- [x] Display a bold title "Restore a backup from IPFS" same css as /new
- [x] Import a new display component called `<display-restore-ipfs>`
- [x] Add a path property to `<display-restore-ipfs path="{{path}}">`
- [x] Create a property 'Path' with an observer that calls a "_path"
- [x] Create a function that sets route.path to be the same as _path

### Unit Tests

- [x]  The <restore-ipfs> display component exists
- [x]  The X Esc button exist
- [x]  Clicking the X button triggers a function

### Visual Test

- [x] The page animation is silky smooth, with no jitter or delay
- [x] The X buttons is in exactly the same location an it is on /new
- [x] The X button is in exactly the same position as /new

**Comment by xardass** [comment]
@bkawk css shared with other pages (pages-new) I could instead add to shared-styles, no?

Also - I had to pull into your branch so I had a working restore page I could navigate from. It could cause conflicts with merge.

**Comment by bkawk** [comment]
Yes as the same css is being used on more than one page it should be moved to shared styles.   
I'm sure we can figure out any merge conficts
