### ISSUE TITLE
New icon (small arrow up) in wiki

### ISSUE THREAD

**Issue by faffydee** [swarmcity/sc-boardwalk-production#203]
For the filter-list, an icon is added to the sprite: the small arrow up. In this case, wiki already updated. [Style-guide page](https://github.com/swarmcity/sc-boardwalk-production/wiki/Style-Guide) is already updated, but the sprite still needs to go in the code.

![swarmcity-sprite-doublesize](https://user-images.githubusercontent.com/24499354/30117237-e1c73abc-931f-11e7-9041-745656979abd.png)

![swarmcity-sprite-normal](https://user-images.githubusercontent.com/24499354/30117238-e1cbf002-931f-11e7-9623-984ea24eb448.png)

**Comment by xardass** [comment]
done
