### ISSUE TITLE
'New here' adjustments

### ISSUE THREAD

**Issue by faffydee** [swarmcity/sc-boardwalk-production#209]
**Routing:**
I think there is something wrong with the route: now it's ".../choose-username/". Shouldn't that be ".../choose-avatar-and-username"? Also, when I try reloading the page it doesn't work.

**General layout changes:**
- [x] Please give the whole page the bg of #F4F3F4
- [x] Change the 'right:30px' to 20px with uploadbutton-container 
- [x] Change the size of uploadbutton-container to 30x30, with the icon being 18x18. Tell me if this need changes in the sprite

**Default layout changes:**
- [x] Make the x-mark into small icon, with color grey2
- [x] Change title color to --grey-3b
- [x] Remove height from bottompart
- [x] Change height of .top to 44vh

**Wide layout changes:**
- [x] Make the x-mark into color grey2
- [x] Change title color to --grey-3b
- [x] I could be mistaken, but I think the --main-title1-wide is not applied
- [x] Remove height from bottompart
- [x] Change height of .top to 44vh
- [x] Distance between avatar+upload and the inputfield is wrong, please doublecheck with Invision

**Comment by xardass** [comment]
- [x] Sprite needs changing to add uploadicon 18x18. We don't resize sprite icons.
- [x] For x-mark small, i think you mean grey3. We have grey4, grey3 and white.
- [x] The title color --grey-3b is new to me? Can you give code value so I can add it?
- [ ] Distance between avatar+upload and the inputfield is wrong, please doublecheck with Invision

FYI the style guide has the correct values for colors and icons (At least how it is in the code). You might want to add the new colors there too.

**Comment by faffydee** [comment]
For the color, I already made an issue for this (= #208 ) when I was making this issue.  I will add the 18x18 icon, that's my bad, I'll fix that now

**Comment by faffydee** [comment]
Changed the sprite so now it has a 18x18 sized uploadicon AND a grey3b X-mark.

**Comment by xardass** [comment]
#207
