### ISSUE TITLE
Sprite update

### ISSUE THREAD

**Issue by faffydee** [swarmcity/sc-boardwalk-production#210]
In this sprite the following is updated:
- changed size of alert-icon (coords remain the same)
- added a 18x18 upload-icon (coords= x: -306px | y: -180px)
- added a grey2 Xmark (coords= x:-108px | y:-234px)
- added a grey3b Xmark (coords = x:-288px | y:-144px)

@n3xco : The files are upload in this issue. If you changed the code, can you also please adjust the Wiki? Or if you want me to do the wiki, give me a sign!

![swarmcity-sprite-doublesize](https://user-images.githubusercontent.com/24499354/30542521-ff0b20ca-9c7f-11e7-826a-0126f3153787.png)
![swarmcity-sprite-normal](https://user-images.githubusercontent.com/24499354/30542520-ff015342-9c7f-11e7-911b-3f15d6bbaf08.png)

**Comment by xardass** [comment]
added to the repo

**Comment by xardass** [comment]
updated wiki

**Comment by xardass** [comment]
#207
