### ISSUE TITLE
Paper-input in SC style

### ISSUE THREAD

**Issue by faffydee** [swarmcity/sc-boardwalk-production#211]
- [x] To make the paper-input in the SC style, this code should be added to shared styles:

(COLORS:)
    --paper-checkbox-unchecked-color: var(--sc-grey4);
    --paper-checkbox-unchecked-ink-color: var(--sc-grey4);
    --paper-checkbox-checkmark-color: var(--sc-white);
    --paper-checkbox-checked-color: var(--sc-blue);
    --paper-checkbox-checked-ink-color: var(--sc-blue);
    --paper-input-container-color: var(--sc-grey4);
    --paper-input-container-focus-color: var(--sc-blue);

(TYPOGRAPHY:)
    --paper-input-container-label: {
        @apply(--body-default);
    };
      --paper-input-error : {
        @apply(--body-bold);
    };
    --paper-input-container-input: {
        @apply(--body-default);
    };
    --paper-input-prefix: {
        @apply(--body-default);
    };
    --paper-input-suffix: {
        @apply(--body-default);
    };

@n3xco : I did have some problems with the typography in the past. If it doesn't work like this, you should put the complete CSS-rules of --body-default here, instead of "@apply(--body-default").

**Comment by xardass** [comment]
The colors worked in shared styles, typo I had to add to the page.

See PR #226

**Comment by faffydee** [comment]
Done by @n3xco
