### ISSUE TITLE
'account-complete' adjustments

### ISSUE THREAD

**Issue by faffydee** [swarmcity/sc-boardwalk-production#219]
- [x] 'backup my account' btn should have white background (described in wiki/shared styles? as fullwhite). In wide-layout it should be 350px
- [x] in wide-layout there should be 70px between the btn and the avatar/username/pubkey

**Comment by xardass** [comment]
White button background is now --sc-white; You prefer just 'white' ?

**Comment by faffydee** [comment]
I actually wanted to create another button-style-mixin. I've made a seperate issue for that, just now (#221)

**Comment by faffydee** [comment]
Minor changes put in new issue (#237) by @n3xco . These adjustements are fixed!
