### ISSUE TITLE
Sprite update

### ISSUE THREAD

**Issue by xardass** [swarmcity/sc-boardwalk-production#264]
- [x] --xmark-blue-small;
- [x] --vmark-white-small;

**Comment by xardass** [comment]
@faffydee

**Comment by faffydee** [comment]
Done. Coords:
--xmark-blue-small (x: -270px | y: -36px);
 --vmark-white-small (x: -270px | y: -72px);

![swarmcity-sprite-normal](https://user-images.githubusercontent.com/24499354/31538960-7119fe8a-b007-11e7-8eb3-ec7577810d56.png)
![swarmcity-sprite-doublesize](https://user-images.githubusercontent.com/24499354/31538961-71323734-b007-11e7-9784-78b61bcf417d.png)
