### ISSUE TITLE
Page Transitions Terminal

### ISSUE THREAD

**Issue by xardass** [swarmcity/sc-boardwalk-production#267]
- [ ] Welcome
- [ ] Language
- [ ] Hashtag List
- [ ] Hashtag
- [ ] Location
- [ ] New Here
- [ ] Restore Account
- [ ] Private Key
- [ ] JSON-File
- [ ] Stop Signup
- [ ] Choose Avatar and Username
- [ ] Resize avatar
- [ ] Password Warning
- [ ] Choose Password
- [ ] Account Complete
- [ ] Make backup
- [ ] My Keys
- [ ] Show private Key
- [ ] Email Success
- [ ] Download Success
- [ ] My Profile
- [ ] Resize avatar
- [ ] Make Backup profile
- [ ] Download success profile
- [ ] Email success profile
- [ ] Warning delete
- [ ] Notifications
- [ ] Wallet view
- [ ] Confirm sending
- [ ] Transaction processing

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#55
