### ISSUE TITLE
Task scheduler complete and refactor tasks

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk-production#279]
1) On start up the task scheduler, schedules n number of tasks,

```
function _taskSheduler(tasks){
    if(taskInProgress == false){   
        taskInProgress = true;
        return tasks.reduce((chain, task) => {
            return chain.then(() => task.toDo(task))
            .then(val => console.log(val));
        }, Promise.resolve());
    }
}
```
https://github.com/swarmcity/infrastructure/blob/master/API/socket.js#L185-L193

After the 4 tasks are complete we need `taskInProgress` to be set to false. Please note that the number of tasks may vary and `taskInProgress` must only become false after all the tasks in the queue have been processed and the end of the promise chain has been reached.

2) All the task functions need to be moved into a new file called tasks.js, the name space in the task scheduler needs adjusting to cater for this refactoring. the functions will still need to be able to call the two log functions, possibly forcing them to be refactored too.

https://github.com/swarmcity/infrastructure/blob/master/API/socket.js#L195-L234

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#45
