### ISSUE TITLE
color of private key

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk-production#282]
Location: page account complete

- [x] the word private key and the underlining shouldn't be blue @faffydee can you give the right color?
- [x] @faffydee can you check in the wiki, about showing private key together with public key, on the wiki it says see visuals how it is ordered, but on the link, i cannot click through. Maybe the designs are in the sketch file. 
- [ ] change the appearance of public private key

**Comment by faffydee** [comment]
I've added the screens now, how it should look when the link "show private key" is tapped, and both keys are visible.

The color of the link is blue.

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#44
