### ISSUE TITLE
copy change

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk-production#297]
Location: Profile page warning delete 
wiki page: https://github.com/swarmcity/sc-boardwalk-production/wiki/warning-delete

Request to change this copy, as agreed with Matt and Faffy

- [ ]  Replace "Do you want to delete this account?" by  "Do you want to delete this account from this device?"
- [ ] Replace "This cannot be undone" by "You can restore this account with your backup."

**Comment by faffydee** [comment]
Yes I approve!

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#37
