### ISSUE TITLE
Visualize all deals a user is involved in (in page-hashtag)

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk-production#311]
- [x] make a list of all different options how a user can be involved in a deal
- [ ] adjust the hashtag page in wiki (https://github.com/swarmcity/sc-boardwalk-production/wiki/Hashtag)

**Comment by faffydee** [comment]
So on page-hashtag, between the top-part (display-my-info + backbtn + hashtagtitle and info + filter) and display-hashtag-deals, there is a space where the user can see the deals of that hashtag in which he is currently involved.

The way each deal appears depends on what state this deal is is. This correlates with some of the dealstates in display-dealstate-detail (https://github.com/swarmcity/sc-boardwalk-production/wiki/Display-Dealstate-Detail) and display-dealstate-mydetail (https://github.com/swarmcity/sc-boardwalk-production/wiki/Display-Dealstate-Mydetail)

Here's a list of possible appearences (correlating states in bold).

1. a request of which I'm the seeker, with no provider selected **(= openrequest)**
2. a request on which I've replied, with no provider selected **(= openrequest)**
3. a request of which I'm the seeker, where I selected a provider to make a deal with **(= providerselected)**
4. a request on which I've replied, where the seeker selected me as the provider **(= providerselected-improvider)**
5. a request on which I've replied, where the seeker selected another user as the provider **(= providerselected-imnotprovider)**
6. a deal the user is in (deal = when both parties are invested) as seeker **(= indeal)**
7. a deal the user is in (deal = when both parties are invested) as provider **(= indeal)**
8. a deal the user is in, that is in conflict (deal = when both parties are invested) as seeker **(= inconflict)**
9. a deal the user is in, that is in conflict (deal = when both parties are invested) as provider **(= inconflict)**
10. a deal that is in conflict, in the hashtag of which the user is hashtagowner

(Screenshots in the next comment)

**Comment by faffydee** [comment]
Not my call, but I thought that a new display would be created for this, a display that takes the dealdata and renders it accordingly.

If we agree on the fact that it will be a new display, then this could be the wiki-page:
https://github.com/swarmcity/sc-boardwalk-production/wiki/Display-Deal-involved

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#30
