### ISSUE TITLE
Remove top bar when adding to homescreen

### ISSUE THREAD

**Issue by kikipluche** [swarmcity/sc-boardwalk-production#314]
When adding the app to your homescreen, there is a bar at the top (where battery and such is): this bar shouldn't be there.

![whatsapp image 2017-11-09 at 12 56 18](https://user-images.githubusercontent.com/9036081/32604542-45d79d5c-c54e-11e7-906f-38a84a779721.jpeg)
![whatsapp image 2017-11-09 at 12 55 51](https://user-images.githubusercontent.com/9036081/32604544-47c57468-c54e-11e7-8ebc-fc3daad3f9a0.jpeg)

> Will wrote:
if this is from viewing the site on android, the grey bar color is set in the manifest or in the index.html

**Comment by faffydee** [comment]
Solution might be here > https://developers.google.com/web/fundamentals/web-app-manifest/

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#29
