### ISSUE TITLE
Conflict-states in display-dealstate-detail

### ISSUE THREAD

**Issue by faffydee** [swarmcity/sc-boardwalk-production#318]
To do the conflict-flow, the component [display-dealstate-detail](https://github.com/swarmcity/sc-boardwalk-production/wiki/Display-Dealstate-Detail) needs a few new state.

Also a 7th and 8th question are added to determine the dealstate:
7. Is the deal put in conflict?
8. Is the deal resolved?

The states would be the following:

////// 
### inconflict:

![dealstate - inconflict - mobile](https://i.imgur.com/0JFQFBN.png)
![dealstate - inconflict - desktop](https://i.imgur.com/x2txxf9.png)

1. yes | 2. yes/no | 3. yes | 4. yes/no | 5. yes | 6. no | 7.yes | 8.no
* **txt (body-bold, grey4):** "This deal is ( > red ) in conflict ( < red )."
* **txt (small-light, grey4):** "The hashtagowner is added to your chat."
* **hashtagowner-avatar (40x40px) + seeker-avatar (40x40px) + provider-avatar (40x40px):** > the order is important, also the overlapping.
* **(CLICKABLE) txt (body-bold, blue):** > count of total chatmsgs > _Route:_ [Deal Chat](https://github.com/swarmcity/sc-boardwalk-production/wiki/deal-chat)
* **(CLICKABLE)  chat-icon (blue, normal)** > _Route:_ [Deal Chat](https://github.com/swarmcity/sc-boardwalk-production/wiki/deal-chat)

////// 
### inconflict-imhashtagowner:

![dealstate - inconflictimhashtagowner - mobile](https://i.imgur.com/ZyEGAp7.png)
![dealstate - inconflictimhashtagowner - desktop](https://i.imgur.com/lc7Il1g.png)

1. yes | 2. yes/no | 3. yes | 4. yes/no | 5. yes | 6. no | 7.yes | 8.no > **CAUTION!:** This is the view the hashtagowner gets to see.

* **txt (body-bold, grey4):** "This deal is ( > red ) in conflict ( < red )."
* **txt (small-light, grey4):** "You are added to this deal to resolve it."
* **hashtagowner-avatar (40x40px) + seeker-avatar (40x40px) + provider-avatar (40x40px):** > the order is important, also the overlapping.
* **(CLICKABLE) txt (body-bold, blue):** > count of total chatmsgs > _Route:_ [Deal Chat](https://github.com/swarmcity/sc-boardwalk-production/wiki/deal-chat)
* **(CLICKABLE)  chat-icon (blue, normal)** > _Route:_ [Deal Chat](https://github.com/swarmcity/sc-boardwalk-production/wiki/deal-chat)
* **line**
* **(CLICKABLE)  Big btn (green):** "resolve"

////// 
### inconflict-resolving:

![dealstate - inconflictresolving - mobile](https://i.imgur.com/KFkIUOy.png)
![dealstate - inconflictresolving - desktop](https://i.imgur.com/wJ9pNUU.png)

1. yes | 2. yes/no | 3. yes | 4. yes/no | 5. yes | 6. no | 7.yes | 8.no> **CAUTION!:** This is the view the hashtagowner gets to see.

* **txt (body-bold, grey4):** "This deal is ( > red ) in conflict ( < red )."
* **txt (small-light, grey4):** "You are added to this deal to resolve it."
* **hashtagowner-avatar (40x40px) + seeker-avatar (40x40px) + provider-avatar (40x40px):** > the order is important, also the overlapping.
* **(CLICKABLE) txt (body-bold, blue):** > count of total chatmsgs > _Route:_ [Deal Chat](https://github.com/swarmcity/sc-boardwalk-production/wiki/deal-chat)
* **(CLICKABLE)  chat-icon (blue, normal)** > _Route:_ [Deal Chat](https://github.com/swarmcity/sc-boardwalk-production/wiki/deal-chat)
* **line**

* **(CLICKABLE) txt (body-bold, green2):** > this number expresses which % the seeker will receive of the total after the conflict is resolved by the hashtagowner
* **(CLICKABLE) txt (body-bold, yellow):** > this number expresses how much SWT the seeker will receive of the total after the conflict is resolved by the hashtagowner
* **seeker-avatar (40x40px)**

* **line with 'handle':** > between the info of the seeker and the info of the provider, we see a line with a green dot (handle) on it. The handle is draggable and is used to make the division of who gets how much. By dragging this handle, the numbers change while the user drags and he is able to make a precise division.

* **(CLICKABLE) txt (body-bold, green2):** > this number expresses which % the provider will receive of the total after the conflict is resolved by the hashtagowner
* **txt (body-bold, yellow):** > this number expresses how much SWT the provider will receive of the total after the conflict is resolved by the hashtagowner
* **provider-avatar (40x40px)**

* **(CLICKABLE)  Icon (X-mark, grey4):** > tapping this will change the state again to "inconflict-imhashtagowner"
* **(CLICKABLE)  Icon-btn (V-mark, blue):** > _Route:_ [Resolve Payout Confirm](https://github.com/swarmcity/sc-boardwalk-production/wiki/resolve-payout-confirm)

////// 
### conflictresolved:

![dealstate - inconflict - mobile](https://i.imgur.com/AQia9Az.png)
![dealstate - inconflict - desktop](https://i.imgur.com/v2KM765.png)

1. yes | 2. yes/no | 3. yes | 4. yes/no | 5. yes | 6. no | 7.yes | 8.yes

* **timestamp (small-light, grey4):** > when conflict was resolved
* **txt (body-bold, grey4):** "Conflict resolved."
* **seeker-avatar (40x40px)**
* **txt (body-default, grey4):** "{{seeker}} was paid {{amount}} SWT. {{seeker}} gained 5 SWR on {{current hashtag}}."
* **provider-avatar (40x40px)**
* **txt (body-default, grey4):** "{{provider}} was paid 1 SWT. {{provider}} gained 5 SWR on {{current hashtag}}."
* **hashtagowner-avatar (40x40px)**
* **txt (body-default, grey4): "{{hashtagowner}} resolved this conflict yesterday, at {{timestamp}}".
* **(CLICKABLE) link (blue):** "see this on etherplorer"

////// 
### conflictresolved-imhashtagowner:

![dealstate - inconflict imhashtagowner - mobile](https://i.imgur.com/9VZVXJ3.png)
![dealstate - inconflict imhashtagowner - desktop](https://i.imgur.com/coNdYeZ.png)

1. yes | 2. yes/no | 3. yes | 4. yes/no | 5. yes | 6. no | 7.yes | 8. yes > **CAUTION!:** This is the view the hashtagowner gets to see.

* **timestamp (small-light, grey4):** > when conflict was resolved
* **txt (body-bold, grey4):** "Conflict resolved."
* **seeker-avatar (40x40px)**
* **txt (body-default, grey4):** "{{seeker}} was paid {{amount}} SWT. {{seeker}} gained 5 SWR on {{current hashtag}}."
* **provider-avatar (40x40px)**
* **txt (body-default, grey4):** "{{provider}} was paid 1 SWT. {{provider}} gained 5 SWR on {{current hashtag}}."
* **hashtagowner-avatar (40x40px)**
* **txt (body-default, grey4): "{{hashtagowner}} resolved this conflict yesterday, at {{timestamp}}".
* **(CLICKABLE) link (blue):** "see this on etherplorer"

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#28
