### ISSUE TITLE
Conflict-states in display-dealstate-mydetail

### ISSUE THREAD

**Issue by faffydee** [swarmcity/sc-boardwalk-production#319]
To do the conflict-flow, the component [display-dealstate-mydetail](https://github.com/swarmcity/sc-boardwalk-production/wiki/Display-Dealstate-Mydetail) also needs a few new state.

In this component, a 5th, 6th and 7th question are added to determine the dealstate:
5. Is this deal of which I am seeker in conflict?
6. Did I resolve the deal by paying out?
7. Is the deal resolved by the hashtagowner?

The states would be the following:

////// 
### inconflict:

![dealstate - inconflict - mobile](https://i.imgur.com/TBGBBb9.png)
![dealstate - inconflict - desktop](https://i.imgur.com/SYjwqVw.png)

1. yes | 2. yes | 3. yes | 4. no | 5. yes | 6. no | 7. no

* **txt (body-bold, grey4):** "This deal is ( > red ) in conflict ( < red )."
* **txt (small-light, grey4):** "The hashtagowner is added to your deal."
* **hashtagowner-avatar (40x40px) + seeker-avatar (40x40px) + provider-avatar (40x40px):** > the order is important, also the overlapping.
* **(CLICKABLE) txt (body-bold, blue):** > count of total chatmsgs > _Route:_ [Deal Chat](https://github.com/swarmcity/sc-boardwalk-production/wiki/deal-chat)
* **(CLICKABLE)  chat-icon (blue, normal)** > _Route:_ [Deal Chat](https://github.com/swarmcity/sc-boardwalk-production/wiki/deal-chat)
**grey2-area with (CLICKABLE)  Big btn (green):** "payout" > _Route:_ [Conflict Payout confirm](https://github.com/swarmcity/sc-boardwalk-production/wiki/conflict-payout-confirm)

////// 
### conflictresolved:

![dealstate - conflictresolved by hashtagowner - mobile](https://i.imgur.com/UDczgae.png)
![dealstate - conflictresolved by hashtagowner - desktop](https://i.imgur.com/4PLCYDv.png)

1. yes | 2. yes | 3. yes | 4. no | 5. yes | 6. yes | 7. no

* **timestamp (small-light, grey4):** > when conflict was resolved
* **txt (body-bold, grey4):** "Conflict resolved."
* **seeker-avatar (40x40px)**
* **txt (body-default, grey4):** "You resolved the conflict by paying out the deal. You received {{amount}} SWR on #pioneer."
* **provider-avatar (40x40px)**
* **txt (body-default, grey4):** "{{provider}} was paid 1 SWT. {{provider}} gained 5 SWR on {{current hashtag}}."
* **hashtagowner-avatar (40x40px)**
* **txt (body-default, grey4): "{{hashtagowner}} was involved, but the conflict was resolved by you."
* **(CLICKABLE) link (blue):** "see this on etherplorer"

////// 
### conflictresolved - by hashtagowner:

![dealstate - conflictresolved - mobile](https://i.imgur.com/AQia9Az.png)
![dealstate - conflictresolved - desktop](https://i.imgur.com/v2KM765.png)

1. yes | 2. yes | 3. yes | 4. no | 5. yes | 6. no | 7. yes

* **timestamp (small-light, grey4):** > when conflict was resolved
* **txt (body-bold, grey4):** "Conflict resolved."
* **seeker-avatar (40x40px)**
* **txt (body-default, grey4):** "{{seeker}} was paid {{amount}} SWT. {{seeker}} gained 5 SWR on {{current hashtag}}."
* **provider-avatar (40x40px)**
* **txt (body-default, grey4):** "{{provider}} was paid 1 SWT. {{provider}} gained 5 SWR on {{current hashtag}}."
* **hashtagowner-avatar (40x40px)**
* **txt (body-default, grey4): "{{hashtagowner}} resolved this conflict yesterday, at {{timestamp}}".
* **(CLICKABLE) link (blue):** "see this on etherplorer"

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#26

**Comment by kikipluche** [comment]
This issue was moved to swarmcity/SwarmCitySite#27
