### ISSUE TITLE
Maintain internationalisation translations 

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk-production#46]
Please can anyone translate the english into as many languages as possible.

    "en": {
        "language": "en",
        "name": "Swarm City",
        "welcome": "Welcome to",
        "enter here": "enter here"
        },
        
    "cn": {
        "language": "cn",
        "name": "一群市",
        "welcome": "欢迎来到",
        "enter here": "在这里输入"
        }

**Comment by kikipluche** [comment]
@bkawk I will take this to slack on our translation channels!

**Comment by xardass** [comment]
I am willing to do the follow-up on this one.

**Comment by bkawk** [comment]
Awesome, as soon as we can approve the clickthrough I can add 95% of the english

**Comment by xardass** [comment]
Localization issue is being handled on getlocalization.com, this can be closed here.
