### ISSUE TITLE
Setup Truffle 

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk-production#60]
Incorporate the truffle project into the sc-boardwalk-production repo. The contracts and migrations folder should be in the root so we have a single package.json 

- [x] initialize truffle by installing it as a dev dependency 
- [ ] setup webpack or truffle-default-builder as the build system (just for the contracts,not for polymer)
- [ ] setup package.json scripts for compile, build deploy and test (just for the contracts,not for polymer)
- [ ] Check that the linter still lints ok `npm run lint` 
- [ ] instal any other dev packages you need as dev dependencies 

The Idea here is that any developer can download the project and be in exactly the same environment quickly and easily by simply running `npm install` and `bower install`

**Comment by sponnet** [comment]
I'd prefer to keep the smart contracts in a separate repo - and have any frontend consume the ABI's from there. I think the smart contracts should be front-end agnostic.

**Comment by bkawk** [comment]
The production repo is for all production code, the separation of concerns can be maintained through branching.
