### ISSUE TITLE
Constant / Static Configuration

### ISSUE THREAD

**Issue by ghost** [swarmcity/sc-boardwalk-production#61]
Should the manifest.json include or another file include configuration attributes like: contract addresses (mainnet, testnet), contract abi definitions, creationBlockNumber for faster eventlog scanning.  

or abi could be dynamically created at build time from contracts, and a contract's creation-block could be looked up rather than predefined in the app.

**Comment by bkawk** [comment]
This requires a bigger vision of where we are going, I yield to @kingflurkel

**Comment by kingflurkel** [comment]
I think we can move forward with whatever solution gives faster loading time. It's not a blocking issue imo, and something we can change as we proceed, test, use.
