### ISSUE TITLE
Writing to IPFS

### ISSUE THREAD

**Issue by bkawk** [swarmcity/sc-boardwalk-production#62]
We face some tough decisions with the IPFS infrastructure. The difficulty does not lie in getting the data from IPFS as we can do this through multiple public nodes, the issue we face is writing the data and persisting it from the browser.

### Favoured Route
Running a node in the browser with js-ipfs gives us access to that user's data only when that user is online. The hash can be sent to a contract but again the file is not persisted.

We need a mechanism to signal to the central IPFS node to pin the generated hash to ensure its persisted. This could be scripted but it may raise questions of centralisation.

We could ask the browser nodes to peer with the central iPFS node to ensure the data is distributed, but is it fair to ask users on a mobile data plan to partake?

We could limit peering to only desktop devices but now we have two IPFS implementations.

We would need a way to signal to the browser that the file has been pinned, effectively letting them know the upload has completed and that they can now disconnect.

### Alternative Routes
1) The public node we are running is writable, I’m finding it hard to accept that we can go into production with this as a solution

2) The other public gateways are also not writable, they too don’t see writable nodes as production ready.

4) Running a node on the users machine permanently, requires an install, enter electron and native alternatives

5) Running a single server for writing data gives us a single point of failure and breaks the decentralized mantra

6) Running many servers and having the DNS route you to the closest one, just for writing to IPFS maybe overkill at this point

**Comment by kingflurkel** [comment]
+1 Favoured Route

**Comment by bkawk** [comment]
The plus one is for two IPFS implementations and the writing of some server script to watch a contract and to pin the found hashes?

**Comment by sponnet** [comment]
Beware that the ipfs protocol is very chatty on the peer maintenance + dht syncing.  I ran a test on a rpi and with an idle (native)  ipfs daemon,  it consumed about 200mb per hour or in that ballpark.. Don't know if that is even feasible on a mobile data plan,  I have no data on how js-ipfs-api behaves with regard to data consumption.  For me a combination of option 3 and 5 plus an incentive mechanism for users to run this software is the ultimate goal. Desktop users don't have the bandwidth limitations and can serve as a swarm of decentralized ipfs nodes.

**Comment by kingflurkel** [comment]
I propose for now we use the ipfs node solution, Sponnet is doing R&D on ipfs-js.

**Comment by sophiii** [comment]
Agree with using ipfs node for now. Even after we have ipfs-js we will need to maintain our node to provide liveness guarantees. 

I was thinking that we could setup/use https://github.com/pipermerriam/ipfs-persistence-consortium for the time being to decentralize our node a little bit. What are the thoughts on that? I think i can get a few other projects interested.

**Comment by kingflurkel** [comment]
Sounds like a plan

**Comment by mschult2** [comment]
I like option 4.

If you don't have a good decentralized solution for any software system component, just centralize it on a server until the point in time where you DO have a confident solution, or other high-priority stuff is done and you can focus on researching that solution. Better than making the wrong decision.

In general, it makes sense to me to isolate and centralize solutions as necessary, and later migrate them to the peer network one solution at a time.

Also: you dont  have one point of failure, at least from a host perspective, if you're using cloud compute platforms. Like EC2 auto-scaling groups, which are distributed across multiple availability zones and auto-deploy in batches. You would have a single point of failure from a governance perspective, tho.

**Comment by bkawk** [comment]
It was finally decided that a bridge from firebase to IPFS would be made, as data is inserted into Firebase that data is then sent to IPFS and hash is returned which is then updated in firebase.
