### ISSUE TITLE
Deploy Current Contracts as a Migration

### ISSUE THREAD

**Issue by ghost** [swarmcity/sc-boardwalk-production#72]
ARC,MiniMeFactory,MiniMe,SWTConverter,MiniMeController
update MiniMeTokenSWT to set a new controller
Hashtag, DealforTwoFactory, hashtag sets factory, set RepToken controller to Hashtag

**Comment by bkawk** [comment]
Once deployed can you make a log of the functions and addresses in the wiki? Maybe make and maintain a new page

**Comment by ghost** [comment]
https://github.com/swarmcity/sc-boardwalk-production/wiki/Smart-Contracts
