### ISSUE TITLE
No hovertext/cursor change/highlight/indication of any kind that icon is clickable

### ISSUE THREAD

**Issue by mschult2** [swarmcity/sc-boardwalk-production#87]
macbook/chrome

Also there is no indication in general how to perform any action on the website. you just kind of click and guess.  Could we make this GUI a little more intuitive? maybe put up a little user documentation on the site?

**Comment by bkawk** [comment]
Mike, thank you for your feedback, The design and UX of the site maintained by @faffydee I will let him explain the design thinking behind the UX.
