### ISSUE TITLE
posting a for-sale item prompt is "what are you looking for" and "what do you offer"

### ISSUE THREAD

**Issue by mschult2** [swarmcity/sc-boardwalk-production#88]
this doesn't make sense, as far as i can tell i just sold something to my friend. his balance went down. so im not "looking" for any good/service, im selling one.

and it's not "what do i offer" it's what im looking to be offered

**Comment by matthewcarano** [comment]
Thanks for the comment. From what I understand, the current live version user experience is from the service seeker perspective. So "What are you looking for" is the seeker question, and "What do you offer" is the seeker's budget. Perhaps a better question would be "What is your budget?".

**Comment by bkawk** [comment]
![screen shot 2017-07-13 at 9 08 43 pm](https://user-images.githubusercontent.com/14357697/28191882-8f92bcba-6865-11e7-80fe-791d53119702.png)

**Comment by mschult2** [comment]
That makes sense. I really wasn't sure at the time though, because it took so long for the transaction to be executed, and subsequent prompts didn't make it clear, especially when money was taken out of the other guy's accounts for the escrow. 

It would've been obvious if the prompt included the word buy or purchase, like "What would you like to buy?"

**Comment by bkawk** [comment]
Valuable feedback, thank you.
