### ISSUE TITLE
Can't access Boardwalk account on iPhone 6

### ISSUE THREAD

**Issue by mschult2** [swarmcity/sc-boardwalk-production#92]
1. Create Swarm.city account on MacBook/Safari. 
2. Get ipfs hash in email.
3. Go to Swarm.city in iPhone/safari.
4. Restore from IPFS hash.
5. No account is found, goes back to "you must be new here" entry screen.
6. Tried to restore from an IPFS hash for another account.
7. Stuck on "downloading from IPFS" screen (20 min, load animation is moving)

**Comment by bkawk** [comment]
I see you are using the backup to and from IPFS as a way of getting the same account on two devices. I know that @sponnet is working on the iPhone issues as we speak.

@sponnet do you have an estimated time to this fix?

**Comment by sponnet** [comment]
I will be looking into this later today, I'm ironing out the last parts (some UI issues) in the Cancel-Deal flow & once this has been sent to the testers, it'll be time to tackle the iOS issues.
It used to work ( albeit quite slow ) on iOS , so whatever is causing this should be fixable. Hope to have an update on this by monday.

**Comment by sponnet** [comment]
btw should this issue be moved to sc-boardwalk ?

**Comment by kikipluche** [comment]
Yes 

Verstuurd vanaf mijn iPhone
