### ISSUE TITLE
Infrastructure-as-code

### ISSUE THREAD

**Issue by mschult2** [swarmcity/sc-boardwalk-production#95]
Migrate all existing service infrastructure to AWS CloudFormation yaml templates. Put in Github repo. 

+transparency!
+enables code reviews, and validation 
+enables version control

**Comment by bkawk** [comment]
@mschult2 I totally agree with you here, there are quite a few solutions out there, Ansible playbooks, CloudFormation and many others have you had any experience with any.

**Comment by mschult2** [comment]
I've messed around with CloudFormation a little. AWS Designer is a decent code/graphical IDE for it, and the yaml syntax is nice. Kind of tedious tho

**Comment by bkawk** [comment]
Maybe Lambda or Google Cloud functions is the way to go?

**Comment by mschult2** [comment]
Seems reasonable that you could use Lambda with the AWS API's to set up your infrastructure.

But note that CloudFormation applies diffs, so you don't end up rolling over your service infrastructure every time you make a change to the config and need to reapply it.  Or if you do in fact want to start over, then you can apply the whole thing. 

To get the same behavior on Lambda, I guess you'd have to write that logic yourself.

**Comment by mschult2** [comment]
Also, I don't think infrastructure-as-code is actually supposed to be code.  Code can have bugs.  

It's supposed to be like markup/yaml configuration files.  These can be version-controlled and programmatically applied, without being susceptible to a class of logical errors like normal code can.

I could also see a domain-specific language being used.

**Comment by bkawk** [comment]
I was considering going infrastructure less and just have lambda functions, I think it would have less moving parts and if we have the same function hosted on aws and google cloud we can have NS1 resolve the DNS to the closest one to the user. The gives speed, reliability and its decentralized.

The servers that demand a full box would just run services proxied by nginx and yes these would need to be scripted as you suggested
