### ISSUE TITLE
 (prod-readiness) Create test stage

### ISSUE THREAD

**Issue by mschult2** [swarmcity/sc-boardwalk-production#96]
Once you have users, you'll need a test stage (aka beta) to validate the integration of new changes before promoting those changes to prod. The test stage should be basically identical to the prod stage, but completely separate (testnet, etc.). the only users should be automated integration tests and testers.

You can automate this in AWS CodePipelines

**Comment by bkawk** [comment]
@mschult2 We have integrated with Travis for the production build, I think CodePipelines is the same, is there any benefit to AWS Pipeline?

**Comment by mschult2** [comment]
I haven't used Travis CI, but prob similar. CodePipelines is a continuous delivery pipeline. It goes:
Github -> build server -> unit tests -> beta deployment stage ->  end to end integration tests -> pros deployment stage

Personally if i have stuff in AWS, then I generally stay in AWS. Their tools work better with each other then with outside tools. Less wiring, more hooks, holistic metrics, etc.
